import type { Contact, Email, Thread } from "./types";

const contacts: Record<string, Contact> = {
  github: { name: "GitHub", email: "notifications@github.com", avatar: "" },
  stripe: { name: "Stripe", email: "receipts@stripe.com", avatar: "" },
  linear: { name: "Linear", email: "notifications@linear.app", avatar: "" },
  vercel: { name: "Vercel", email: "ship@vercel.com", avatar: "" },
  alice: { name: "Alice Chen", email: "alice@company.com", avatar: "" },
  bob: { name: "Bob Martinez", email: "bob@company.com", avatar: "" },
  carol: { name: "Carol Williams", email: "carol@company.com", avatar: "" },
  dave: { name: "Dave Park", email: "dave@company.com", avatar: "" },
  eve: { name: "Eve Johnson", email: "eve@company.com", avatar: "" },
  frank: { name: "Frank Liu", email: "frank@company.com", avatar: "" },
  substack: { name: "The Pragmatic Engineer", email: "gergely@pragmaticengineer.com", avatar: "" },
  dense: { name: "Dense Discovery", email: "kai@densediscovery.com", avatar: "" },
  tldr: { name: "TLDR Newsletter", email: "dan@tldrnewsletter.com", avatar: "" },
  producthunt: { name: "Product Hunt", email: "hello@producthunt.com", avatar: "" },
  figma: { name: "Figma", email: "team@figma.com", avatar: "" },
  aws: { name: "Amazon Web Services", email: "no-reply@aws.amazon.com", avatar: "" },
  me: { name: "Fenil Sonani", email: "fenil@fenilsonani.com", avatar: "" },
  sarah: { name: "Sarah Kim", email: "sarah@agency.co", avatar: "" },
  notion: { name: "Notion", email: "team@notion.so", avatar: "" },
  slack: { name: "Slack", email: "feedback@slack.com", avatar: "" },
};

const now = new Date();
function daysAgo(n: number) {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}
function hoursAgo(n: number) {
  const d = new Date(now);
  d.setHours(d.getHours() - n);
  return d.toISOString();
}
function minsAgo(n: number) {
  const d = new Date(now);
  d.setMinutes(d.getMinutes() - n);
  return d.toISOString();
}

export const emails: Email[] = [
  // Thread 1: Alice — Project Kickoff (3 messages)
  {
    id: "e1",
    threadId: "t1",
    from: contacts.alice,
    to: [contacts.me],
    subject: "Project Veil — Kickoff Meeting Tomorrow",
    body: `<p>Hey Fenil,</p><p>Just a reminder that we have the kickoff meeting for Project Veil tomorrow at 10 AM. I've shared the design brief in Figma — please take a look before the meeting so we can hit the ground running.</p><p>The main goals for v1 are:</p><ul><li>Three-pane layout with resizable panels</li><li>Threaded conversations with beautiful typography</li><li>Command palette as the primary navigation paradigm</li><li>AI-assisted email triage</li></ul><p>Let me know if you have any questions!</p><p>Best,<br/>Alice</p>`,
    snippet: "Just a reminder that we have the kickoff meeting for Project Veil tomorrow at 10 AM...",
    date: daysAgo(1),
    read: false,
    starred: true,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [],
    aiSummary: "Alice is reminding you about tomorrow's Project Veil kickoff at 10 AM",
    aiPriority: "action",
    suggestedReplies: ["I'll review the Figma tonight!", "Sounds great, see you at 10", "Can we push to 11 AM?"],
  },
  {
    id: "e1b",
    threadId: "t1",
    from: contacts.me,
    to: [contacts.alice],
    subject: "Re: Project Veil — Kickoff Meeting Tomorrow",
    body: `<p>Thanks Alice! I've been looking at the designs — they look fantastic. The serif typography approach for the reading pane is really elegant.</p><p>One question: are we going with Instrument Serif or did you consider Playfair Display?</p><p>See you tomorrow!</p>`,
    snippet: "Thanks Alice! I've been looking at the designs — they look fantastic...",
    date: hoursAgo(20),
    read: true,
    starred: false,
    folder: "sent",
    category: "primary",
    labels: ["Work"],
    attachments: [],
    replyTo: "e1",
  },
  {
    id: "e1c",
    threadId: "t1",
    from: contacts.alice,
    to: [contacts.me],
    subject: "Re: Project Veil — Kickoff Meeting Tomorrow",
    body: `<p>Great question! We're going with Instrument Serif — it has better screen rendering and the contrast works beautifully at 18px. Playfair was too heavy for body text.</p><p>Also, I've added Carol to the meeting. She'll handle the motion design system.</p>`,
    snippet: "Great question! We're going with Instrument Serif — it has better screen rendering...",
    date: hoursAgo(18),
    read: false,
    starred: false,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [],
    aiSummary: "Alice confirms Instrument Serif for typography and added Carol for motion design",
    aiPriority: "info",
    replyTo: "e1b",
  },

  // Thread 2: GitHub PR Review
  {
    id: "e2",
    threadId: "t2",
    from: contacts.github,
    to: [contacts.me],
    subject: "[email-server] Pull Request #18: feat(webmail): add preview server",
    body: `<p><strong>bob</strong> requested your review on <a href="#">#18 feat(webmail): add preview server</a></p><p>This PR adds a preview server for the webmail interface with hot-reload support.</p><p><strong>Files changed:</strong> 12<br/><strong>Additions:</strong> +847<br/><strong>Deletions:</strong> -23</p>`,
    snippet: "bob requested your review on #18 feat(webmail): add preview server",
    date: hoursAgo(3),
    read: false,
    starred: false,
    folder: "inbox",
    category: "updates",
    labels: ["Work"],
    attachments: [],
    aiSummary: "Bob needs your code review on the webmail preview server PR (+847/-23)",
    aiPriority: "action",
    suggestedReplies: ["I'll review this afternoon", "Looks good, approving now", "Left some comments"],
  },

  // Thread 3: Stripe receipt
  {
    id: "e3",
    threadId: "t3",
    from: contacts.stripe,
    to: [contacts.me],
    subject: "Your receipt from Vercel Inc.",
    body: `<p>Hi Fenil,</p><p>Your payment of <strong>$20.00</strong> to Vercel Inc. was successful.</p><table style="width:100%;border-collapse:collapse;margin:16px 0"><tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Vercel Pro Plan</td><td style="text-align:right;padding:8px 0">$20.00</td></tr><tr style="border-top:2px solid #333"><td style="padding:8px 0;font-weight:bold">Total</td><td style="text-align:right;padding:8px 0;font-weight:bold">$20.00</td></tr></table>`,
    snippet: "Your payment of $20.00 to Vercel Inc. was successful.",
    date: hoursAgo(5),
    read: true,
    starred: false,
    folder: "inbox",
    category: "updates",
    labels: ["Finance"],
    attachments: [{ id: "a1", name: "receipt-2026-03.pdf", size: 48200, type: "application/pdf" }],
    aiSummary: "Stripe processed your $20.00 payment to Vercel for the Pro Plan",
    aiPriority: "info",
  },

  // Thread 4: Bob — Architecture discussion (2 messages)
  {
    id: "e4",
    threadId: "t4",
    from: contacts.bob,
    to: [contacts.me, contacts.alice],
    subject: "Zustand vs Jotai — state management for Veil",
    body: `<p>Hey team,</p><p>I've been prototyping both approaches. Here's my take:</p><p><strong>Zustand:</strong></p><ul><li>Single store, simple API</li><li>Great devtools</li><li>Easy to test</li></ul><p><strong>Jotai:</strong></p><ul><li>Atomic, fine-grained reactivity</li><li>Better for derived state</li><li>More boilerplate</li></ul><p>I'm leaning Zustand for simplicity. The mail state is fairly flat — we don't need atomic updates. Thoughts?</p>`,
    snippet: "I've been prototyping both approaches. I'm leaning Zustand for simplicity...",
    date: hoursAgo(8),
    read: true,
    starred: true,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [],
    aiSummary: "Bob recommends Zustand over Jotai for Veil's state management",
    aiPriority: "action",
    suggestedReplies: ["Agreed, let's go with Zustand", "What about Redux Toolkit?", "Can you share the prototype?"],
  },
  {
    id: "e4b",
    threadId: "t4",
    from: contacts.alice,
    to: [contacts.bob, contacts.me],
    subject: "Re: Zustand vs Jotai — state management for Veil",
    body: `<p>+1 for Zustand. I've used it in three production apps and it's been rock solid. The middleware for persistence is also handy if we want to cache mail state in localStorage.</p><p>Let's finalize this in tomorrow's kickoff.</p>`,
    snippet: "+1 for Zustand. I've used it in three production apps and it's been rock solid...",
    date: hoursAgo(6),
    read: true,
    starred: false,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [],
    replyTo: "e4",
  },

  // Thread 5: The Pragmatic Engineer newsletter
  {
    id: "e5",
    threadId: "t5",
    from: contacts.substack,
    to: [contacts.me],
    subject: "How Big Tech Runs Production: The SRE Model in 2026",
    body: `<p>This week, I dive into how Google, Meta, and Stripe have evolved their SRE practices. The biggest shift? <strong>AI-assisted incident response</strong> is now standard at all three companies.</p><p>Key takeaways:</p><ul><li>Automated runbooks have reduced MTTR by 40%</li><li>LLM-powered log analysis catches issues before alerts fire</li><li>The "SRE" title is being replaced by "Production Engineer" at Meta</li></ul><p><a href="#">Read the full article →</a></p>`,
    snippet: "This week, I dive into how Google, Meta, and Stripe have evolved their SRE practices...",
    date: hoursAgo(12),
    read: false,
    starred: false,
    folder: "inbox",
    category: "newsletters",
    labels: ["Newsletters"],
    attachments: [],
    aiSummary: "Pragmatic Engineer covers how Big Tech has evolved SRE with AI-assisted incident response",
    aiPriority: "info",
  },

  // Thread 6: Product Hunt — Daily digest
  {
    id: "e6",
    threadId: "t6",
    from: contacts.producthunt,
    to: [contacts.me],
    subject: "🚀 Today's Top Products — March 5, 2026",
    body: `<p><strong>Today's #1 Product:</strong></p><p>✨ <strong>Veil Mail</strong> — The email client that makes reading emails beautiful<br/>An editorial-inspired email client with serif typography, spatial animations, and AI triage.</p><p><strong>#2:</strong> CodeBrew — AI pair programmer for terminal<br/><strong>#3:</strong> PixelSnap 3.0 — Screenshot tool with auto-annotations</p>`,
    snippet: "Today's #1 Product: Veil Mail — The email client that makes reading emails beautiful",
    date: hoursAgo(14),
    read: true,
    starred: false,
    folder: "inbox",
    category: "promotions",
    labels: [],
    attachments: [],
    aiSummary: "Product Hunt daily digest featuring Veil Mail as the #1 product",
    aiPriority: "info",
  },

  // Thread 7: Linear notification
  {
    id: "e7",
    threadId: "t7",
    from: contacts.linear,
    to: [contacts.me],
    subject: "VEIL-42: Implement command palette has been assigned to you",
    body: `<p><strong>Carol Williams</strong> assigned <a href="#">VEIL-42: Implement command palette</a> to you.</p><p><strong>Priority:</strong> Urgent<br/><strong>Label:</strong> Frontend<br/><strong>Due:</strong> March 8, 2026</p><p>Description: Build the cinematic full-screen command palette with backdrop blur, spring animations, and grouped search results.</p>`,
    snippet: "Carol Williams assigned VEIL-42: Implement command palette to you.",
    date: hoursAgo(2),
    read: false,
    starred: false,
    folder: "inbox",
    category: "updates",
    labels: ["Work"],
    attachments: [],
    aiSummary: "You've been assigned VEIL-42: command palette implementation, due March 8",
    aiPriority: "urgent",
    suggestedReplies: ["On it!", "Can we extend the deadline?", "I'll start after the kickoff"],
  },

  // Thread 8: Carol — Motion design
  {
    id: "e8",
    threadId: "t8",
    from: contacts.carol,
    to: [contacts.me],
    cc: [contacts.alice],
    subject: "Motion design tokens for Veil",
    body: `<p>Hi Fenil,</p><p>I've put together the motion design tokens for Veil. Here's the system:</p><pre><code>// Spring presets
const spring = {
  gentle: { stiffness: 120, damping: 20 },
  snappy: { stiffness: 300, damping: 30 },
  bouncy: { stiffness: 400, damping: 15 },
}

// Duration tokens
const duration = {
  instant: 0.1,
  fast: 0.2,
  normal: 0.3,
  slow: 0.5,
}

// Easing
const ease = {
  out: [0.16, 1, 0.3, 1],
  inOut: [0.65, 0, 0.35, 1],
}</code></pre><p>The key principle: <em>everything uses spring physics except opacity transitions</em>. No linear or ease-in-out for position/scale.</p><p>Attached the full motion spec PDF.</p>`,
    snippet: "I've put together the motion design tokens for Veil. The key principle: everything uses spring physics...",
    date: daysAgo(2),
    read: true,
    starred: true,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [{ id: "a2", name: "veil-motion-spec.pdf", size: 2340000, type: "application/pdf" }],
    aiSummary: "Carol shares motion design tokens — spring physics for all position/scale animations",
    aiPriority: "action",
    suggestedReplies: ["These look perfect!", "Can we add a preset for page transitions?", "I'll integrate these today"],
  },

  // Thread 9: Vercel deployment
  {
    id: "e9",
    threadId: "t9",
    from: contacts.vercel,
    to: [contacts.me],
    subject: "✅ Deployment successful — veil-mail.vercel.app",
    body: `<p>Your deployment to <strong>production</strong> was successful.</p><p><strong>Project:</strong> veil-mail<br/><strong>Domain:</strong> veil-mail.vercel.app<br/><strong>Branch:</strong> main<br/><strong>Commit:</strong> feat: initial three-pane layout</p><p><strong>Build time:</strong> 12.3s<br/><strong>Functions:</strong> 4<br/><strong>Edge functions:</strong> 1</p>`,
    snippet: "Your deployment to production was successful. Domain: veil-mail.vercel.app",
    date: daysAgo(3),
    read: true,
    starred: false,
    folder: "inbox",
    category: "updates",
    labels: [],
    attachments: [],
    aiSummary: "Vercel successfully deployed veil-mail to production (12.3s build)",
    aiPriority: "info",
  },

  // Thread 10: Dense Discovery newsletter
  {
    id: "e10",
    threadId: "t10",
    from: contacts.dense,
    to: [contacts.me],
    subject: "Dense Discovery — Issue 287",
    body: `<p>Welcome to this week's Dense Discovery.</p><p><strong>Apps & Sites</strong></p><ul><li><a href="#">Linear 2.0</a> — The redesigned project management tool</li><li><a href="#">Raycast AI</a> — Your Mac launcher, now with AI built in</li></ul><p><strong>Design</strong></p><ul><li>The return of skeuomorphism in Apple's visionOS design language</li><li>Why Material Design 3 adoption remains slow</li></ul>`,
    snippet: "Welcome to this week's Dense Discovery. Apps & Sites: Linear 2.0, Raycast AI...",
    date: daysAgo(4),
    read: true,
    starred: false,
    folder: "inbox",
    category: "newsletters",
    labels: ["Newsletters"],
    attachments: [],
    aiSummary: "Weekly Dense Discovery newsletter covering Linear 2.0, Raycast AI, and design trends",
    aiPriority: "info",
  },

  // Thread 11: Dave — Bug report
  {
    id: "e11",
    threadId: "t11",
    from: contacts.dave,
    to: [contacts.me],
    subject: "Bug: Sidebar collapse animation jitters on Safari",
    body: `<p>Hey Fenil,</p><p>Found a bug in the sidebar collapse animation. On Safari 17.4, the panel resize causes a layout shift that makes the animation stutter.</p><p>Steps to reproduce:</p><ol><li>Open Veil in Safari</li><li>Click the sidebar collapse button</li><li>Watch the mail list panel — it jumps about 4px during the transition</li></ol><p>I think the issue is that we're animating width instead of using transform. Let me know if you want me to take a look.</p>`,
    snippet: "Found a bug in the sidebar collapse animation. On Safari 17.4, the panel resize causes a layout shift...",
    date: hoursAgo(1),
    read: false,
    starred: false,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [],
    aiSummary: "Dave reports a Safari animation bug — sidebar collapse causes 4px layout shift",
    aiPriority: "urgent",
    suggestedReplies: ["Good catch, I'll fix it today", "Can you record a video?", "Let's use transform instead of width"],
  },

  // Thread 12: TLDR
  {
    id: "e12",
    threadId: "t12",
    from: contacts.tldr,
    to: [contacts.me],
    subject: "TLDR: OpenAI releases GPT-5, React 20 announced",
    body: `<p><strong>Big Tech & Startups</strong></p><p>OpenAI released GPT-5 with native multimodal understanding. Performance on coding benchmarks improved 30% over GPT-4o.</p><p><strong>Developer</strong></p><p>React 20 announced at React Conf with built-in server components, zero-config bundling, and a new compiler that eliminates the need for useMemo/useCallback.</p>`,
    snippet: "OpenAI released GPT-5 with native multimodal understanding. React 20 announced...",
    date: daysAgo(1),
    read: false,
    starred: false,
    folder: "inbox",
    category: "newsletters",
    labels: ["Newsletters"],
    attachments: [],
    aiSummary: "TLDR covers GPT-5 release and React 20 announcement with built-in server components",
    aiPriority: "info",
  },

  // Thread 13: Figma comment
  {
    id: "e13",
    threadId: "t13",
    from: contacts.figma,
    to: [contacts.me],
    subject: "Sarah Kim commented on 'Veil — Command Palette'",
    body: `<p><strong>Sarah Kim</strong> commented on your design <em>Veil — Command Palette</em>:</p><blockquote><p>"Love the frosted glass effect! Can we make the search input auto-focus with a slight scale animation? Maybe start at 0.98 and spring to 1.0."</p></blockquote><p><a href="#">View in Figma →</a></p>`,
    snippet: "Sarah Kim commented: Love the frosted glass effect! Can we make the search input auto-focus...",
    date: hoursAgo(4),
    read: false,
    starred: false,
    folder: "inbox",
    category: "updates",
    labels: [],
    attachments: [],
    aiSummary: "Sarah suggests adding a scale spring animation to the command palette search input",
    aiPriority: "info",
    suggestedReplies: ["Great idea, I'll add that!", "Already implemented 😎", "Let me prototype it"],
  },

  // Thread 14: AWS
  {
    id: "e14",
    threadId: "t14",
    from: contacts.aws,
    to: [contacts.me],
    subject: "Your AWS bill for February 2026",
    body: `<p>Hello Fenil Sonani,</p><p>Your AWS usage charges for February 2026:</p><table style="width:100%;border-collapse:collapse;margin:16px 0"><tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Amazon SES</td><td style="text-align:right;padding:8px 0">$4.50</td></tr><tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Amazon Route 53</td><td style="text-align:right;padding:8px 0">$1.00</td></tr><tr style="border-top:2px solid #333"><td style="padding:8px 0;font-weight:bold">Total</td><td style="text-align:right;padding:8px 0;font-weight:bold">$5.50</td></tr></table>`,
    snippet: "Your AWS usage charges for February 2026: Total $5.50",
    date: daysAgo(5),
    read: true,
    starred: false,
    folder: "inbox",
    category: "updates",
    labels: ["Finance"],
    attachments: [{ id: "a3", name: "aws-invoice-feb-2026.pdf", size: 156000, type: "application/pdf" }],
    aiSummary: "AWS bill for February: $5.50 (SES $4.50 + Route 53 $1.00)",
    aiPriority: "info",
  },

  // Thread 15: Eve — Design review
  {
    id: "e15",
    threadId: "t15",
    from: contacts.eve,
    to: [contacts.me, contacts.alice],
    subject: "Design review: Empty states & onboarding",
    body: `<p>Team,</p><p>I've designed the empty states for all folders. Each one has a unique illustration and contextual copy:</p><ul><li><strong>Inbox zero:</strong> A peaceful sunrise illustration with "You're all caught up"</li><li><strong>Drafts:</strong> A blank canvas with "Your drafts will appear here"</li><li><strong>Trash:</strong> A clean desk with "Nothing in the trash"</li><li><strong>Search:</strong> A magnifying glass with "No results for [query]"</li></ul><p>I'm also working on a first-run experience. New users will see a brief tutorial highlighting the command palette, keyboard shortcuts, and split inbox.</p><p>Figma link in the attachment.</p>`,
    snippet: "I've designed the empty states for all folders. Each one has a unique illustration and contextual copy...",
    date: daysAgo(2),
    read: true,
    starred: false,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [{ id: "a4", name: "empty-states-v2.fig", size: 4500000, type: "application/octet-stream" }],
    aiSummary: "Eve shares empty state designs for all folders plus first-run onboarding experience",
    aiPriority: "info",
    suggestedReplies: ["These are beautiful!", "Can we add animations to the illustrations?", "Love the inbox zero state"],
  },

  // Thread 16: Frank — Backend question
  {
    id: "e16",
    threadId: "t16",
    from: contacts.frank,
    to: [contacts.me],
    subject: "IMAP IDLE vs WebSocket for real-time updates?",
    body: `<p>Hey Fenil,</p><p>Quick architecture question. For real-time email updates in Veil, should we:</p><ol><li><strong>IMAP IDLE</strong> — Direct connection to IMAP server, push notifications on new mail. Pros: standard protocol, works with any IMAP server. Cons: one connection per folder, complex reconnection logic.</li><li><strong>WebSocket bridge</strong> — Backend service that monitors IMAP and pushes to client via WebSocket. Pros: single connection, custom events, works through firewalls. Cons: extra service to maintain.</li></ol><p>I'm leaning toward option 2 since we already have the Go backend.</p>`,
    snippet: "Quick architecture question. For real-time email updates, should we use IMAP IDLE or WebSocket bridge?",
    date: daysAgo(3),
    read: true,
    starred: true,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [],
    aiSummary: "Frank asks about IMAP IDLE vs WebSocket for real-time updates, recommends WebSocket",
    aiPriority: "action",
    suggestedReplies: ["WebSocket bridge for sure", "Let's discuss in the kickoff", "Can you prototype both?"],
  },

  // Thread 17: Notion workspace
  {
    id: "e17",
    threadId: "t17",
    from: contacts.notion,
    to: [contacts.me],
    subject: "Weekly summary: Veil workspace activity",
    body: `<p>Here's your weekly summary for the <strong>Veil</strong> workspace:</p><ul><li>12 pages updated</li><li>3 new pages created</li><li>Top contributor: Alice Chen (8 edits)</li><li>Most viewed: "Veil — Technical Architecture" (23 views)</li></ul>`,
    snippet: "Weekly summary: 12 pages updated, 3 new pages created. Top contributor: Alice Chen",
    date: daysAgo(1),
    read: true,
    starred: false,
    folder: "inbox",
    category: "updates",
    labels: [],
    attachments: [],
    aiSummary: "Notion weekly: 12 pages updated, Alice Chen top contributor, architecture doc most viewed",
    aiPriority: "info",
  },

  // Thread 18: Sarah — Freelance project
  {
    id: "e18",
    threadId: "t18",
    from: contacts.sarah,
    to: [contacts.me],
    subject: "Potential project: Dashboard redesign for FinFlow",
    body: `<p>Hi Fenil,</p><p>I'm reaching out because I've seen your work on Veil and I'm impressed. We have a client (FinFlow, a fintech startup) who needs their analytics dashboard redesigned.</p><p>Budget: $8,000–$12,000<br/>Timeline: 4 weeks<br/>Stack: Next.js + Tailwind + D3</p><p>Would you be interested in discussing? I can set up a call this week.</p><p>Best,<br/>Sarah</p>`,
    snippet: "I'm reaching out about a dashboard redesign project for FinFlow. Budget: $8,000–$12,000...",
    date: hoursAgo(7),
    read: false,
    starred: true,
    folder: "inbox",
    category: "primary",
    labels: ["Personal"],
    attachments: [],
    aiSummary: "Sarah offers a freelance dashboard redesign project ($8K-$12K, 4 weeks, Next.js)",
    aiPriority: "action",
    suggestedReplies: ["I'd love to discuss!", "My schedule is tight right now", "Can you share more about FinFlow?"],
  },

  // Thread 19: Slack notification
  {
    id: "e19",
    threadId: "t19",
    from: contacts.slack,
    to: [contacts.me],
    subject: "New messages in #veil-dev",
    body: `<p>You have 5 unread messages in <strong>#veil-dev</strong>:</p><p><strong>Carol:</strong> "Just pushed the sidebar animation fix. Can someone review?"<br/><strong>Bob:</strong> "The virtualized list is so smooth now 🔥"<br/><strong>Dave:</strong> "Anyone else seeing a flicker on the compose modal?"<br/><strong>Alice:</strong> "Sprint planning at 3pm, don't forget"<br/><strong>Bob:</strong> "Merged the Zustand store PR!"</p>`,
    snippet: "5 unread messages in #veil-dev: Carol pushed sidebar fix, Bob merged Zustand PR...",
    date: hoursAgo(1),
    read: false,
    starred: false,
    folder: "inbox",
    category: "updates",
    labels: [],
    attachments: [],
    aiSummary: "5 messages in #veil-dev — sidebar fix pushed, sprint planning at 3pm, Zustand PR merged",
    aiPriority: "info",
  },

  // Sent emails
  {
    id: "e20",
    threadId: "t20",
    from: contacts.me,
    to: [contacts.alice, contacts.bob],
    subject: "Weekend deploy plan",
    body: `<p>Hey team,</p><p>I'm planning to deploy the v0.2 build this weekend. The key changes are:</p><ul><li>Command palette with full search</li><li>Keyboard navigation (j/k/o)</li><li>Split inbox categories</li><li>AI summary badges</li></ul><p>I'll run through the checklist Saturday morning and deploy by noon. Alice — can you be on standby for any design issues?</p>`,
    snippet: "I'm planning to deploy the v0.2 build this weekend. Key changes: command palette, keyboard nav...",
    date: daysAgo(2),
    read: true,
    starred: false,
    folder: "sent",
    category: "primary",
    labels: ["Work"],
    attachments: [],
  },

  // Draft
  {
    id: "e21",
    threadId: "t21",
    from: contacts.me,
    to: [contacts.sarah],
    subject: "Re: Potential project: Dashboard redesign for FinFlow",
    body: `<p>Hi Sarah,</p><p>Thanks for reaching out! The FinFlow project sounds interesting. I'd love to learn more about the requirements.</p><p>A few questions:</p><ul><li>What's the current tech stack?</li><li>Do you have existing design mockups?</li><li></li></ul>`,
    snippet: "Thanks for reaching out! The FinFlow project sounds interesting...",
    date: hoursAgo(2),
    read: true,
    starred: false,
    folder: "drafts",
    category: "primary",
    labels: [],
    attachments: [],
  },

  // Archived
  {
    id: "e22",
    threadId: "t22",
    from: contacts.vercel,
    to: [contacts.me],
    subject: "Your trial has been extended",
    body: `<p>Hi Fenil,</p><p>Great news! Your Vercel Pro trial has been extended by 14 days. Continue building amazing things.</p>`,
    snippet: "Your Vercel Pro trial has been extended by 14 days.",
    date: daysAgo(10),
    read: true,
    starred: false,
    folder: "archive",
    category: "promotions",
    labels: [],
    attachments: [],
  },

  // Trash
  {
    id: "e23",
    threadId: "t23",
    from: contacts.producthunt,
    to: [contacts.me],
    subject: "You've been invited to launch on Product Hunt",
    body: `<p>Hi Fenil, you've been invited to launch your product on Product Hunt. Get in front of thousands of early adopters.</p>`,
    snippet: "You've been invited to launch your product on Product Hunt.",
    date: daysAgo(7),
    read: true,
    starred: false,
    folder: "trash",
    category: "promotions",
    labels: [],
    attachments: [],
  },

  // More primary emails
  {
    id: "e24",
    threadId: "t24",
    from: contacts.carol,
    to: [contacts.me],
    subject: "Framer Motion v12 migration notes",
    body: `<p>Hey,</p><p>I finished migrating our animations to Framer Motion v12. Key changes:</p><ul><li><code>AnimatePresence</code> now supports exit animations on server components</li><li><code>useMotionValue</code> is more performant with the new scheduling system</li><li>The <code>layout</code> prop works perfectly for our shared element transitions</li></ul><p>No breaking changes for our codebase. PR is up for review.</p>`,
    snippet: "I finished migrating our animations to Framer Motion v12. No breaking changes for our codebase...",
    date: minsAgo(30),
    read: false,
    starred: false,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [],
    aiSummary: "Carol migrated to Framer Motion v12 — no breaking changes, PR ready for review",
    aiPriority: "action",
    suggestedReplies: ["I'll review the PR now", "Any performance improvements?", "Nice work!"],
  },

  // More newsletters
  {
    id: "e25",
    threadId: "t25",
    from: { name: "Bytes", email: "bytes@ui.dev", avatar: "" },
    to: [contacts.me],
    subject: "Bytes: The spiciest TypeScript drama of 2026",
    body: `<p>Your weekly dose of JavaScript news that doesn't take itself too seriously.</p><p><strong>The Drama:</strong> TypeScript 6.0 dropped and broke half the ecosystem's build configs. Again.</p><p><strong>The Cool:</strong> Bun 2.0 now supports full Node.js compatibility, including native C++ addons.</p><p><strong>The Weird:</strong> Someone built a full email client with only CSS. It actually works.</p>`,
    snippet: "TypeScript 6.0 dropped and broke half the ecosystem. Bun 2.0 now supports full Node.js compatibility...",
    date: daysAgo(2),
    read: true,
    starred: false,
    folder: "inbox",
    category: "newsletters",
    labels: ["Newsletters"],
    attachments: [],
    aiSummary: "Bytes newsletter: TypeScript 6.0 breaks builds, Bun 2.0 gets full Node compat",
    aiPriority: "info",
  },

  // Promotions
  {
    id: "e26",
    threadId: "t26",
    from: { name: "Raycast", email: "hello@raycast.com", avatar: "" },
    to: [contacts.me],
    subject: "Raycast Pro — 50% off for early adopters",
    body: `<p>Hey Fenil,</p><p>As a Raycast power user, we'd like to offer you <strong>50% off Raycast Pro</strong> for the first year.</p><p>What's included:</p><ul><li>AI commands with Claude integration</li><li>Cloud sync for snippets and quicklinks</li><li>Custom themes and advanced extensions</li></ul><p><a href="#">Claim your discount →</a></p>`,
    snippet: "50% off Raycast Pro for the first year. Includes AI commands, cloud sync, custom themes...",
    date: daysAgo(3),
    read: true,
    starred: false,
    folder: "inbox",
    category: "promotions",
    labels: [],
    attachments: [],
    aiSummary: "Raycast offering 50% off Pro plan — AI commands, cloud sync, custom themes",
    aiPriority: "info",
  },

  {
    id: "e27",
    threadId: "t27",
    from: { name: "Tailwind Labs", email: "team@tailwindcss.com", avatar: "" },
    to: [contacts.me],
    subject: "Tailwind CSS v4.1 is here",
    body: `<p>Tailwind CSS v4.1 is out with some features we think you'll love:</p><ul><li>Container queries support with <code>@container</code></li><li>New color functions: <code>oklch()</code> and <code>color-mix()</code></li><li>Automatic dark mode detection</li><li>50% faster builds with the new Oxide engine</li></ul><p><a href="#">Read the release notes →</a></p>`,
    snippet: "Tailwind CSS v4.1 is out: container queries, oklch colors, 50% faster builds...",
    date: daysAgo(6),
    read: true,
    starred: true,
    folder: "inbox",
    category: "newsletters",
    labels: ["Newsletters"],
    attachments: [],
    aiSummary: "Tailwind v4.1 released with container queries, oklch colors, and Oxide engine (50% faster)",
    aiPriority: "info",
  },

  // More work emails
  {
    id: "e28",
    threadId: "t28",
    from: contacts.eve,
    to: [contacts.me],
    subject: "Accessibility audit results",
    body: `<p>Fenil,</p><p>Ran the accessibility audit on the current build. Overall score: <strong>94/100</strong>. Issues found:</p><ol><li><strong>Critical:</strong> Command palette lacks <code>aria-label</code> on search input</li><li><strong>Major:</strong> Mail list items missing <code>role="listitem"</code></li><li><strong>Minor:</strong> Color contrast on muted text is 3.8:1 (need 4.5:1)</li></ol><p>Items 1 and 2 are easy fixes. For item 3, I suggest bumping the muted foreground from <code>oklch(0.547)</code> to <code>oklch(0.58)</code>.</p>`,
    snippet: "Accessibility audit score: 94/100. Three issues found, two easy fixes...",
    date: minsAgo(45),
    read: false,
    starred: false,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [],
    aiSummary: "Accessibility audit: 94/100 — needs aria-label, role attributes, and contrast fix",
    aiPriority: "action",
    suggestedReplies: ["I'll fix the critical and major today", "Great score!", "Should we target 100?"],
  },

  // GitHub CI notification
  {
    id: "e29",
    threadId: "t29",
    from: contacts.github,
    to: [contacts.me],
    subject: "[veil-mail] CI: All checks passed on feat/command-palette",
    body: `<p>All CI checks passed on branch <code>feat/command-palette</code>:</p><ul><li>✅ Build (12.1s)</li><li>✅ Lint (3.2s)</li><li>✅ Type Check (4.8s)</li><li>✅ Unit Tests — 47 passed (8.9s)</li><li>✅ E2E Tests — 12 passed (23.4s)</li></ul><p><a href="#">View workflow run →</a></p>`,
    snippet: "All CI checks passed: Build ✅ Lint ✅ Type Check ✅ 47 unit tests ✅ 12 E2E tests ✅",
    date: hoursAgo(6),
    read: true,
    starred: false,
    folder: "inbox",
    category: "updates",
    labels: [],
    attachments: [],
    aiSummary: "All CI checks passed on command palette branch — 47 unit + 12 E2E tests green",
    aiPriority: "info",
  },

  // Old starred email
  {
    id: "e30",
    threadId: "t30",
    from: contacts.bob,
    to: [contacts.me],
    subject: "Performance benchmarks — initial numbers",
    body: `<p>Ran the initial performance benchmarks:</p><table style="width:100%;border-collapse:collapse;margin:16px 0"><tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">First Contentful Paint</td><td style="text-align:right;padding:8px 0">0.8s</td></tr><tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Largest Contentful Paint</td><td style="text-align:right;padding:8px 0">1.2s</td></tr><tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Time to Interactive</td><td style="text-align:right;padding:8px 0">1.4s</td></tr><tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Bundle Size (gzipped)</td><td style="text-align:right;padding:8px 0">127 KB</td></tr></table><p>These are solid numbers. The virtualized list handles 10,000 emails without dropping below 60fps.</p>`,
    snippet: "Initial benchmarks: FCP 0.8s, LCP 1.2s, TTI 1.4s, Bundle 127KB. Virtualized list handles 10K emails at 60fps.",
    date: daysAgo(7),
    read: true,
    starred: true,
    folder: "inbox",
    category: "primary",
    labels: ["Work"],
    attachments: [],
    aiSummary: "Performance benchmarks: FCP 0.8s, LCP 1.2s, 127KB bundle, 60fps with 10K emails",
    aiPriority: "info",
  },
];

// Build threads from emails
function buildThreads(): Thread[] {
  const threadMap = new Map<string, Email[]>();
  for (const email of emails) {
    const existing = threadMap.get(email.threadId) || [];
    existing.push(email);
    threadMap.set(email.threadId, existing);
  }

  return Array.from(threadMap.entries()).map(([id, threadEmails]) => {
    const sorted = threadEmails.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
    const last = sorted[sorted.length - 1];
    const participants = Array.from(
      new Map(sorted.flatMap((e) => [e.from, ...e.to]).map((c) => [c.email, c])).values()
    );
    return {
      id,
      subject: sorted[0].subject.replace(/^Re:\s*/i, ""),
      emails: sorted,
      participants,
      lastDate: last.date,
      unreadCount: sorted.filter((e) => !e.read).length,
      starred: sorted.some((e) => e.starred),
      category: sorted[0].category,
      folder: last.folder,
      labels: [...new Set(sorted.flatMap((e) => e.labels))],
      aiSummary: last.aiSummary,
      aiPriority: last.aiPriority,
    };
  });
}

export const threads = buildThreads();

export const allContacts: Contact[] = Object.values(contacts);
